### PR TITLE
fix: Prevent `query->count` from changing query internals

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).

### Issue Description

The current query->count function overrides the limit and count conditions. This prevents the query from being used after the count operation occurs and may return unintended results. This could be worked around by using `withCount`.

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by dplewis** [comment]
@mtrezza Since https://github.com/parse-community/parse-php-sdk/pull/510 got merged, I updated the tests to show query internals haven't been changed.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.3.2](https://github.com/parse-community/parse-php-sdk/releases/tag/2.3.2)

**Pull request merged**
