### PR TITLE
Release 1.4.0  🐘

### PR DESCRIPTION
**Pull request by montymxb**
Preparatory changes for release **1.4.0**.

### CODE REVIEW

**Comment by montymxb** [comment]
CI issue noted running against parse server **2.7.1**. I'll address that separately and merge into this before pushing this release.

**Comment by dplewis** [comment]
Update the Readme to 1.4.*
```
{
    "require": {
        "parse/php-sdk" : "1.3.*"
    }
}
```

Update `ParseInstallationTest.php` don't know if this is important
`$parseVersion   = '1.3.0';`

**Comment by montymxb** [comment]
@dplewis thanks for catching the README, almost missed that. As for the test that's not really needed, but it's nice to just keep it in track with the current sdk version. I went ahead and set it to use the version # from **VERSION_STRING** in **ParseClient.php**.

**Comment by dplewis** [comment]
Sorry, I'm going to steal this from you 
:octocat: approved

**Comment by montymxb** [comment]
Just to note I'll rectify w/e is going on with the CI here so we I can finish this release out tonight.

**Pull request merged**
