### PR TITLE
ci: Fix manual documentation release

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-php-sdk/issues/495

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this ready for merge?

**Comment by dplewis** [comment]
Yes, let’s see if it works

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by mtrezza** [comment]
The workflow succeeded.

**Comment by mtrezza** [comment]
See https://github.com/parse-community/parse-php-sdk/issues/495#issuecomment-1524733096

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.1.0](https://github.com/parse-community/parse-php-sdk/releases/tag/2.1.0)

**Pull request merged**
