### PR TITLE
alternate method to remove auth data 

### PR DESCRIPTION
**Pull request by acinader**
Has the added benefit of working with current versions of mongo :).

I copied this from https://github.com/parse-community/parse-server/blob/master/spec/ParseUser.spec.js#L2640

see: https://github.com/parse-community/parse-php-sdk/pull/427#issuecomment-458722990

### CODE REVIEW

**Comment by flovilmart** [comment]
LGTM!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
Can you check that authData->anonymous == null?

Your current test only shows that all authData is gone.

**Comment by acinader** [comment]
@dplewis I don't understand.

I set it to null so it'll be removed, so there's no authData to check.

**Comment by dplewis** [comment]
@acinader nvm, I didn't know this was happening on the back end.

https://github.com/parse-community/parse-server/blob/master/src/RestWrite.js#L1519

Looks good to me!

**Pull request merged**
