### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by montymxb** [comment]
I'll have to tinker with this to get the builds passing, but thanks for setting this up again!

**Comment by flovilmart** [comment]
@montymxb I checked the CONTRIBUTING.md file and try to set it up accordingly we'll see :)

**Comment by montymxb** [comment]
I was just looking at those changes. I think that should do it! Essentially composer/npm wrap up our dependencies, and **npm start** fires up the test server. Assuming the server can bind and is reachable we'll have to see how Travis works with it...

**Comment by flovilmart** [comment]
we need node 6 installed and it ships with node 0.10... nvm is no installed either

**Comment by montymxb** [comment]
brew isn't present either :/, I think there's an easier way to load up npm. I think there's a built in way to include it, I'm looking at the moent.

**Comment by flovilmart** [comment]
ok! Don't hesitate to edit updateSessionUpdateTime on that branch directly.

**Comment by montymxb** [comment]
It looks like nvm is actually installed, as it gave `N/A version is not installed yet`. But it looks like if you want to set it up you can run it under the `before_install` section. No guarantees but it would seem to work.

```json
before_install:
  - nvm install 6.0
```

**Comment by flovilmart** [comment]
Ahah it works! But there are some PHP errors: 

``` 
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/travis/build/parse-community/parse-php-sdk/tests/Parse/AddOperationTest.php on line 43
```

**Comment by montymxb** [comment]
Progress! I'll take a quick look and patch that syntax issue up. As for the other tests looks like syntax is acceptable but the server is not reachable.

`Parse\ParseException: couldn't connect to host`

Either it's running or it's not able to connect, with the process in the background it's hard to tell. I'll see what I can do about that.

**Comment by flovilmart** [comment]
it's possible that the server is not running anymore :/

**Comment by montymxb** [comment]
Ahhh, good catch. We may have to manually include that dependency if Travis CI is missing it for some reason, assuming that's the issue.

**Comment by flovilmart** [comment]
yeah that's odd

**Comment by montymxb** [comment]
Probably, they don't seem to be a problem when we're not running travis but it certainly wouldn't hurt.

**Comment by montymxb** [comment]
I'll leave them in this package.json for the moment, just to get this sorted out. Once that looks good I'll shift them down as a dependency in the **parse-server-test** repo.

**Comment by flovilmart** [comment]
@montymxb Awesome Job man! That's rocking! I just added the codecov badge and travis!

**Comment by flovilmart** [comment]
That’s awesome! From the coverage perspective the SDK is one of the best we have! Glad we can get the CI to help out. If you need anything else, I’m just round the corner!

**Comment by montymxb** [comment]
@flovilmart thanks again for helping get Travis setup! That's fantastic to hear we're one of the most covered sdks too 💯 . Always good to keep the test coverage up!

**Comment by flovilmart** [comment]
No problem! Glad to help!

**Pull request merged**
